RATINGS_FILE = "archive/ratings.csv"
MOVIES_FILE = "archive/movies.csv"
RECOMMENDATION_TOP_K = 10
MAX_USERS = 50
MAX_SIMILAR_USERS = 1
DEFAULT_DROP_DOWN_USER_ID = 5
EVALUATION_TOP_K = 10
EVALUATION_USER_LIMIT = 50
TRAIN_TEST_SPLIT_RATIO = 0.8

