RATINGS_FILE = "archive/ratings.csv"
MOVIES_FILE = "archive/movies.csv"
RECOMMENDATION_TOP_K = 10
MAX_USERS = 50
GRAPH_MAX_USERS_PER_MOVIE = 1
DEFAULT_DROP_DOWN_USER_ID = 5
EVALUATION_TOP_K = 10
EVALUATION_USER_LIMIT = 50
TRAIN_TEST_SPLIT_RATIO = 0.8
CONTENT_BASED_MIN_SIMILARITY = 0.15
CONTENT_BASED_MIN_RATERS = 30
CONTENT_BASED_MIN_RATING = 4.0
COLLABORATIVE_MIN_COMMON_MOVIES = 3
SAME_GENRE_MIN_RATERS = 30
SAME_GENRE_MIN_RATING = 3.8

