import os

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
DATASETS_DIR = 'datasets'
DATASETS_PATH = os.path.join(PROJECT_ROOT, DATASETS_DIR)
BOOKINGS_FILE = f'{DATASETS_DIR}/bookings.csv'
EVENTS_FILE = f'{DATASETS_DIR}/events.csv'
WEATHER_FILE = f'{DATASETS_DIR}/weather.csv'

API_PORT = 8000
DASHBOARD_PORT = 8501

DEFAULT_FORECAST_PERIODS = 30
DEFAULT_RECOMMENDATIONS = 5
DEFAULT_ITINERARY_DAYS = 3
DEFAULT_EVENTS_PER_DAY = 3
DEFAULT_RECOMMENDATION_DAYS = 10

PERSONAS_CLUSTERS = 3
RANDOM_STATE = 42
SIMILAR_USERS_COUNT = 10

DATASET_START_DATE = '2023-12-01'
DATASET_END_DATE = '2026-02-28'

DATASET_N_ACCOMMODATIONS = 50
DATASET_BASE_BOOKINGS_PER_DAY = 100
DATASET_MIN_BOOKINGS_PER_DAY = 50
DATASET_MAX_BOOKINGS_PER_DAY = 200

RECOMMENDATION_START_DATE = '2024-06-01'
CONTROL_GROUP_PERCENTAGE = 0.2

# Impact modeling parameters
BASE_REPEAT_PROBABILITY = 0.3
CONTROL_RETENTION_DROP = 0.7
CONVERSION_BASE_RATE = 0.05
CONVERSION_BOOST_RATE = 0.15
BASE_CLICK_RATE = 0.15
BASE_CONVERSION_RATE = 0.08

# Dataset pollution configuration
ENABLE_DATASET_POLLUTION = False
POLLUTION_MISSING_RATE = 0.075  # 5-10% per column (using midpoint)
POLLUTION_OUTLIER_RATE = 0.015  # 1-2% (using midpoint)
POLLUTION_DUPLICATE_RATE = 0.015  # 1-2% (using midpoint)
POLLUTION_TYPE_ERROR_RATE = 0.035  # 2-5% (using midpoint)

